
version: '3.1'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-5.7
    ports:
      - "4406:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=000000
    networks:
      - canalsharp
    volumes:
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./var/lib/mysql:/var/lib/mysql
      - ./mysql/init/:/docker-entrypoint-initdb.d/
      - ./var/log:/var/log/mysql/


  canal-server:
    image: canal/canal-server:latest
    platform: linux/amd64
    container_name: canal-server
    ports:
      - "11111:11111"
      - "11110:11110"
      - "11112:11112"
    environment:
     - canal.admin.port=11110
     - canal.admin.user=admin
     - canal.destinations=example
     - canal.admin.manager=canal-admin:8089
     - canal.admin.passwd=6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9
    networks:
      - canalsharp
    volumes:
      - ./example/:/home/admin/canal-server/conf/example/
      - ./canal-server-logs/:/home/admin/canal-server/logs/
    depends_on:
      - mysql
  canal-adapter:
    image: funnyzak/canal-adapter:1.1.6
    container_name: canal-adapter
    platform: linux/amd64
    restart: on-failure
    volumes:
      - ./canal/canal-adapter/conf:/opt/canal/canal-adapter/conf
      - ./canal/canal-adapter/logs:/opt/canal/canal-adapter/logs
    depends_on:
      - canal-server
      - elasticsearch
      - mysql
    networks:
      - canalsharp

  elasticsearch:
    image: elasticsearch:7.5.0
    platform: linux/amd64
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-cluster-ai66
      - "discovery.type=single-node" #以单一节点模式启动
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs/
     # - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300

    restart: always
    networks:
      - canalsharp
  kibana:
    image: kibana:7.5.0
    platform: linux/amd64
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - canalsharp
  canal-admin:
    image: canal/canal-admin:latest
    platform: linux/amd64
    ports:
      - 8089:8089
    depends_on:
      - canal-server
      - mysql
    environment:
      - server.port=8089
      - canal.adminUser=admin
      - canal.adminPasswd=123456
    networks:
      - canalsharp
networks:

  canalsharp:
    driver: bridge

